[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "SAMEORIGIN"
    Cache-Control = "no-cache, no-store, must-revalidate"

[[redirects]]
  from = "/"
  to = "/client.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
